### ISSUE TITLE
Failure to build on Julia 0.7, Windows 7 x64 

### ISSUE THREAD

**Issue by RodolfoFigueroa** [JuliaGraphics/Cairo.jl#265]
Cairo refuses to build on julia 0.7.0, running on Windows 7 x86_64-w64-mingw32. This is the package manager output:

```
(v0.7) pkg> build Cairo
  Building LibCURL ─→ `C:\Users\Rodolfo\.julia\packages\LibCURL\OoXMv\deps\build.log`
  Building WinRPM ──→ `C:\Users\Rodolfo\.julia\packages\WinRPM\Y9QdZ\deps\build.log`
  Building Homebrew → `C:\Users\Rodolfo\.julia\packages\Homebrew\l8kUw\deps\build.log`
  Building Cairo ───→ `C:\Users\Rodolfo\.julia\packages\Cairo\CXPG1\deps\build.log`
┌ Error: Error building `Cairo`:
│ [ Info: Updating WinRPM package list
│ [ Info: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
│ [ Info: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
│ [ Info: Nothing to do
│ ERROR: LoadError: Provider WinRPM.RPM failed to satisfy dependency pangocairo
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\Rodolfo\.julia\packages\BinDeps\ZEval\src\dependencies.jl:945
│  [3] satisfy!(::BinDeps.LibraryGroup, ::Array{DataType,1}) at C:\Users\Rodolfo\.julia\packages\BinDeps\ZEval\src\dependencies.jl:910
│  [4] satisfy!(::BinDeps.LibraryGroup) at C:\Users\Rodolfo\.julia\packages\BinDeps\ZEval\src\dependencies.jl:874
│  [5] top-level scope at C:\Users\Rodolfo\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [6] include at .\boot.jl:317 [inlined]
│  [7] include_relative(::Module, ::String) at .\loading.jl:1038
│  [8] include(::Module, ::String) at .\sysimg.jl:29
│  [9] include(::String) at .\client.jl:398
│  [10] top-level scope at none:0
│ in expression starting at C:\Users\Rodolfo\.julia\packages\Cairo\CXPG1\deps\build.jl:165
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068
```

Evaluating with BinDeps.debug() produces the following output:

```
julia> BinDeps.debug("Cairo")
The package declares 1 dependencies.
 - Library Group "cairo"
     - Library "png" (not applicable to this system)
     - Library "pixman" (not applicable to this system)
     - Library "ffi" (not applicable to this system)
     - Library "gettext" (not applicable to this system)
     - Library "gobject"
        - Satisfied by:
          - WinRPM.RPM package ["glib2", "libgobject-2_0-0"] at C:\Users\Rodolfo\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libgobject-2.0-0.dll
        - Providers:
          - WinRPM.RPM package ["glib2", "libgobject-2_0-0"]
          - AptGet package libglib2.0-0 (can't provide)
          - Yum package glib2 (can't provide)
          - Zypper package libglib-2_0 (can't provide)
          - Autotools Build
     - Library "freetype" (not applicable to this system)
     - Library "fontconfig" (not applicable to this system)
     - Library "cairo"
        - Satisfied by:
          - WinRPM.RPM package ["libcairo2", "libharfbuzz0"] at C:\Users\Rodolfo\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libcairo-2.DLL
        - Providers:
          - WinRPM.RPM package ["libcairo2", "libharfbuzz0"]
          - AptGet package libcairo2 (can't provide)
          - Yum package cairo (can't provide)
          - Zypper package libcairo2 (can't provide)
          - Autotools Build
     - Library "pango"
        - Satisfied by:
          - WinRPM.RPM package libpango-1_0-0 at C:\Users\Rodolfo\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\libpango-1.0-0.dll
        - Providers:
          - WinRPM.RPM package libpango-1_0-0
          - AptGet package libpango1.0-0 (can't provide)
          - Yum package pango (can't provide)
          - Zypper package libpango-1_0 (can't provide)
          - Autotools Build
     - Library "pangocairo"
        - Providers:
          - WinRPM.RPM package libpango-1_0-0
          - AptGet package libpango1.0-0 (can't provide)
          - Yum package pango (can't provide)
          - Zypper package libpango-1_0 (can't provide)
          - Autotools Build
     - Library "zlib"
        - Satisfied by:
          - WinRPM.RPM package zlib-devel at C:\Users\Rodolfo\.julia\packages\WinRPM\Y9QdZ\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\zlib1.DLL
          - System Paths at C:\Users\Rodolfo\AppData\Local\Julia-0.7.0\bin\zlib1.DLL
        - Providers:
          - WinRPM.RPM package zlib-devel
          - Simple Build Process
```

I am aware of similar issues like #261. However, there are no conflicting directories in the PATH environment variable.
